version: "3.8"
services:
  backend:
    build: .
    container_name: workshop-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma db push && npm run dev"
